version: '3'

services:
  mg-identity-service:
    image: mg-identity-service:latest
    hostname: mg-identity-service
    env_file: .env
    build:
      dockerfile: Dockerfile
    environment:
      - spring.jpa.hibernate.ddl-auto=update
    ports:
      - '8080:8080'
    networks:
      - mgi-backend-wrapper-network
    depends_on:
      - postgres
      - swagger-ui

  postgres:
    image: postgres:14.1-alpine
    hostname: postgres-mg-identity-service
    restart: always
    environment:
      POSTGRES_URL: ${DATASOURCE_URL}
      POSTGRES_DB: ${DATASOURCE_DB}
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    ports:
      - '5432:5432'
    networks:
      - mgi-backend-wrapper-network
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8079:8079"
    environment:
      SWAGGER_JSON: /data/swagger.yml
    networks:
      - mgi-backend-wrapper-network
    volumes:
      - ./data:/data

networks:
  mgi-backend-wrapper-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local