service:
  access-token:
    lifetime: ${ACCESS_TOKEN_LIFETIME}
    private-key-path: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
    public-key-path: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
  refresh-token:
    lifetime: ${REFRESH_TOKEN_LIFETIME}
    private-key-path: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
    public-key-path: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}
  verification-properties:
    lifetime: ${VERIFICATION_LIFETIME}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG

server:
  port: ${APPLICATION_PORT}

spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        retries: 2147483647
        retry.backoff.ms: 1000
        acks: all
        enable.idempotence: true
    consumer:
      group-id: mg-identity-service-kafka-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        session.timeout.ms: 45000
        heartbeat.interval.ms: 15000
        max.poll.interval.ms: 300000
    bootstrap-servers: event-router-kafka:29092

  application:
    name: ${APPLICATION_PROJECT_NAME}

  main:
    banner-mode: off

  datasource:
    driverClassName: org.postgresql.Driver
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}

  jpa:
    open-in-view: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: mg-identity-service
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://mg-gateway-server-service:8761/eureka/

springdoc:
  api-docs:
    enabled: true
    path: /identity/public/v3/api-docs
  swagger-ui:
    enabled: false