service:
  access-token:
    lifetime: ${ACCESS_TOKEN_LIFETIME}
    private-key-path: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
    public-key-path: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
  refresh-token:
    lifetime: ${REFRESH_TOKEN_LIFETIME}
    private-key-path: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
    public-key-path: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG

server:
  port: ${APPLICATION_PORT}

spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: kafka:29092

  application:
    name: ${APPLICATION_PROJECT_NAME}

  main:
    banner-mode: off

  datasource:
    driverClassName: org.postgresql.Driver
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}

  jpa:
    open-in-view: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /identity-mg/v3/api-docs/index.html