name: Prepare application before a commit
on:
  push:
    branches:
      - dev
      -
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Build with Gradlew
        run: .\gradlew clean build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2

        with:
          name: java-app
          path: '${{ github.workspace }}/mg-identity-service-spring/build/libs/mg-identity-service-spring.jar'

      - name: Run Tests
        run: .\gradlew testClasses